### PR TITLE
Add SystemD service

### PR DESCRIPTION
**Pull request by trinitronx**
This adds a SystemD user service for `findex-daemon`.  When enabled, it starts linked to `graphical-session.target`.  This should be relatively desktop agnostic, except for users who don't use SystemD at all.  Otherwise, for SystemD systems it's simple to enable it:

```console
$ systemctl enable --user findex-daemon.service
Created symlink '/home/exampleuser/.config/systemd/user/graphical-session.target.wants/findex-daemon.service' → '/usr/lib/systemd/user/findex-daemon.service'.
```

On next graphical session start, the `findex-daemon` will automatically start along with it.  To manually start for the first time after installing the `.service` unit:

```console
$ systemctl start --user findex-daemon.service
```

```console
$ systemctl status --user findex-daemon.service
● findex-daemon.service - Findex Daemon
     Loaded: loaded (/usr/lib/systemd/user/findex-daemon.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-08-08 19:05:40 MDT; 3s ago
 Invocation: ad44a88b0876459880a31ed8da377289
    Process: 3020878 ExecStart=/usr/bin/findex-daemon (code=exited, status=0/SUCCESS)
   Main PID: 3020888 (findex-daemon)
      Tasks: 10 (limit: 76959)
     Memory: 40.7M (peak: 44.6M)
        CPU: 742ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/findex-daemon.service
             ├─3020888 /usr/bin/findex-daemon
             └─3020889 findex

Aug 08 19:05:39 saturn systemd[970]: Starting Findex Daemon...
Aug 08 19:05:40 saturn systemd[970]: Started Findex Daemon.
```

### CODE REVIEW

**Comment by trinitronx** [comment]
@mdgaziur To add this to the AUR `PKGBUILD`, [a simple change is needed][1].

Also, FYI: I noticed an issue with the current `findex-git` `PKGBUILD` where it installs the `style.css` to a file literally named `/opt/findex`, instead of the intended path: `/opt/findex/style.css`.  [That fix is here][2].  Feel free to pull both of these changes from my archlinux.org remote GitLab repo.  I left two branches up for this:

- [`add-systemd-service`][3] - Adds the SystemD service.  Also, based on `fix-missing-css` branch below (so diff against `upstream/master` includes those changes).
- [`fix-missing-css`][4] - Fixes the installation of `style.css`.


[1]: https://gitlab.archlinux.org/trinitronx/findex-git/-/merge_requests/2/diffs
[2]: https://gitlab.archlinux.org/trinitronx/findex-git/-/merge_requests/1/diffs
[3]: https://gitlab.archlinux.org/trinitronx/findex-git/-/compare/upstream-master...add-systemd-service?from_project_id=84413&straight=false
[4]: https://gitlab.archlinux.org/trinitronx/findex-git/-/compare/upstream-master...fix-missing-css?from_project_id=84413&straight=false

**Comment by mdgaziur** [comment]
Hi! Sorry for the delayed response. Findex daemon was made so that users won't need systemd to start Findex on startup and restart Findex in case it crashes for some reason. Can you please show me reasons why you want a systemd service for Findex to be added?

**Comment by trinitronx** [comment]
> Hi! Sorry for the delayed response. Findex daemon was made so that users won't need systemd to start Findex on startup and restart Findex in case it crashes for some reason. Can you please show me reasons why you want a systemd service for Findex to be added?

Sure! I'd be happy to explain:

While some users may prefer to either avoid SystemD, and/or launch or manage apps like Findex in their own way....  In some cases, and for those choosing SystemD, it would be preferable for the lifetime of `findex-daemon` and thus `findex` to be linked to the lifetime of the user graphical session (via `user.slice` & `session-*.scope`) & managed appropriately via a service manager.  It's common on Unix OS's for server daemons at the system or OS-level to be managed by `init` / `PID 1`, for example a webserver or some service that is necessary for the Operating System.  Historically, graphical applications were launched and managed by Xorg / `.Xsession`, or else some other graphical session manager such as GDM, `gnome-session`, and others.

However it's also now becoming increasingly common on Linux for user-level services to be managed by SystemD too using the built-in `--user` service manager.  Doing this also allows for obtaining multiple benefits:

1. Allows decoupling the process tree of some tools from being managed by a desktop environment or session manager (e.g. Sway, `gnome-session`, etc...)
2. Solves the [Zombie process reaping problem][1]
  - There are some cases where a process dies but becomes a "zombie" (a.k.a. `defunct process`). Zombie processes must be periodically reaped, which is something that `PID 1` (or whatever assumes it's role) is supposed to do.
  - If the pool of possible `PID`s is exhausted, it can starve the entire OS for `PID`s when new processes are created (thus making it unusable or unstable).
  - Often, graphical desktop session managers or simple shell scripts don't perform this function, leaving zombie `PID`s around.
3. Allows for Highly Available recovery through automatic restarts
  - Service managers such as SystemD often implement an automatic restart with backoff timing logic
  - This can help in cases where an application crashes or otherwise misbehaves by restarting it to try and recover and restore the service to an operational state.
  - In other words: This allows for a basic level of high availability and level-of-service recovery, in the event that a process dies or is killed for some other reason than stopping it via `systemctl stop --user ...` (e.g. killed by [OOM Killer][2], `SEGFAULT`s, accidentally killed by another process or user running `killall ...`)
  - **Specifically for this app**: In the case of `findex-daemon`, it appears that some level of restarting for `findex` is already implemented [when config files change][8].  That is an excellent feature!  Although, in the event that `findex-daemon` itself dies for some undesired reason, then we are still left in a situation where it would not restart.  (e.g. we are left in a "Who watches the watcher" kind of situation)
4. Allows for and opens the door to using common service manager features, which in SystemD include:
  - Using [`Type=notify`][3] + [`systemd-notify`][4] and/or [`sd_notify()`][5] to signal the service manager when the daemon is fully ready (avoids startup [race conditions][6])
  - Start up services in parallel according to their dependencies
    - Allows for faster startup when compared to a serially launched list from a graphical session manager
    - These speed benefits are obtained through multiprocessing
    - Also it's best if something downstream depends on your service to use `sd_notify` and `Type=notify` to signal when ready (avoids the [race condition][6] problem)
  - Service logs automatically get sent to JournalD (For example: viewable via `journalctl -xen100 --user-unit findex-daemon.service`)
    - Log rotation / persistence is handled by JournalD (avoids filling up disk with logs & causing system instability)
    - Allows for handling logs in a central place, and makes centralized logging easier to implement.
    - Allows for system users and administrators to more easily see what is happening on their systems by looking in one place. (Very helpful to see order that things happened when debugging an issue)
  - Allows for Resource management & limits, as well as process grouping for services, which can more easily be managed through SystemD
5. Adding a SystemD service unit file also helps downstream packagers.
  - It gives them some recommended default `.service` file(s), which they can choose to include verbatim, or use as a basis for further patching or customization for their OS-level distro packages.
  - In other words: It's good form as an app developer to have one or else for users to submit one as a PR / contribution (often you'll see one in some `systemd`, `contrib/` or equivalent dir).
6. The [directory precedence][7] system allows the user to have some control over their SystemD services by adding user unit overrides in `$XDG_CONFIG_HOME/systemd/user/`
  - If the distro packager ships a SystemD unit in the system directories (`/usr/{local/,}lib/systemd`), then the end-user can choose to disable or "mask" a unit in their `$XDG_CONFIG_HOME` SystemD dir if they want to opt out from using it.
  - On distros such as Arch Linux, the packages usually do not enable services by default, instead relying on the user to decide to opt-in to using the SystemD unit.  In this case, nothing is needed to override if they simply want to opt-out of using SystemD.
  - On distros such as Ubuntu & Debian, the packages will usually enable the services by default.  This gives a more "batteries included" type of experience, while still allowing for overrides & masking through the directory inheritance priority ordering.

I hope this helps explain the rationale for this. 😄

[1]: https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/
[2]: https://neo4j.com/developer/kb/linux-out-of-memory-killer/
[3]: https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#Type=
[4]: https://www.freedesktop.org/software/systemd/man/latest/systemd-notify.html
[5]: https://www.freedesktop.org/software/systemd/man/latest/sd_notify.html#
[6]: https://www.techtarget.com/searchstorage/definition/race-condition
[7]: https://man.archlinux.org/man/systemd.unit.5.en#System_Unit_Search_Path
[8]: https://github.com/mdgaziur/findex/blob/development/crates/findex-daemon/src/main.rs#L54-L67

**Comment by mdgaziur** [comment]
This seems like a good idea. I'll test this and then let you know about my
decision :3

**Review by mdgaziur — APPROVED** [review]

**Comment by mdgaziur** [comment]
Hi, can you update the installer to copy the service files to appropriate place? I didn't notice that part and erroneously merged this PR(sorry for that). I think if you open another PR with the suggested changes it should be good to go. Sorry for the inconvenience :'(
Edit: I've merged the changes in this PR. You can create a new PR with the changes I've suggested :^)

**Pull request merged**
