### PR TITLE
Don't crash on missing icon (Fix #1)

### LINKED ISSUE #1: Some assumptions don't hold on non-FHS distros
Hey,

I've tried to play a bit with Findex on NixOS (a non-FHS linux distribution), and hit two bugs:

 - `query.rs:13` hardcodes `/usr/share/applications/`, which doesn't exist on Nix/Guix. I'm not sure what's the portable way to find this path, I suspect it's something like enumerating `$XDG_DATA_DIRS`.
 - The program crashes when an icon is missing in the current theme. This is probably an issue with my config, but crashing seems a bit of an extreme reaction :) (and such finders often are used in minimal setups, so missing icons *will* happen.

Regards,

### PR DESCRIPTION
**Pull request by thblt**

### CODE REVIEW

**Comment by mdgaziur** [comment]
I'll merge after testing

**Comment by mdgaziur** [comment]
umm, I couldn't actually get "application-other" to not exist on my system. Can you send a screenshot?
Sorry for making too much comment

**Comment by mdgaziur** [comment]
Set the value of height and width parameter to 32. Will merge after that :)

**Comment by thblt** [comment]
> Set the value of height and width parameter to 32. Will merge after that :)
> 
I assumed 1x1 would be safer if you ended up making icon sizes configurable or something.

**Comment by mdgaziur** [comment]
My main goal is to add basic features and then move to adding more ways to customize :)

**Pull request merged**
