### PR TITLE
Added ability to remove in installer.sh

### PR DESCRIPTION
**Pull request by chent7**
As per title.
Please let me know if any changes should be done.

PS:
Decided on a different implementation for removing after looking at the code.
There is no helpscreen (look at branch name)

### CODE REVIEW

**Comment by mdgaziur** [comment]
/opt/findex/style.css isn't meant for the user. User should use ~/.config/findex/style.css. Update the pr please :^)

**Comment by mdgaziur** [comment]
I will make proper readme soon. Didn't expect the repo to gain popularity this fast.

**Comment by chent7** [comment]
The repo was in my Google feed. Expect more soon. Best wishes.

**Comment by chent7** [comment]
> /opt/findex/style.css isn't meant for the user. User should use ~/.config/findex/style.css. Update the pr please :^)

Do you want to remove asking a second time?

**Comment by mdgaziur** [comment]
Yes

**Comment by chent7** [comment]
done

**Pull request merged**
